aws:
  region: us-east-1
  kinesis:
    stream-name: my-stream
    application-name: kinesis-dynamodb-consumer
  dynamodb:
    table-name: my-table
  endpoint: http://localhost:4566  # LocalStack endpoint

spring:
  application:
    name: kinesis-dynamodb-consumer

logging:
  level:
    root: INFO
    com.example.kinesis: DEBUG
    software.amazon.kinesis: DEBUG
    software.amazon.awssdk: DEBUG
